apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-demo
  namespace: default
  labels:
    app: nacos-demo
spec:
  selector:
    matchLabels:
      app: nacos-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: nacos-demo
      annotations:
        enable.version-checker.io/busybox: "true"
    spec:
      containers:
      - name: nacos-demo
        image: harbor.harmay.com/912988434/java-demo:master-45
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: harbor

